#spring.application.name=journal
#spring.data.mongodb.uri=mongodb+srv://programmer:GncGLNJAxzdXm568@userjournal.jewesfh.mongodb.net/?appName=UserJournal
#spring.data.mongodb.database=journal
#spring.data.mongodb.auto-index-creation=true